const data = {
    products: [
        {
            name: 'Free Shirt',
            slug: 'free-shirt',
            category: 'Shirts',
            image: '/images/shirt1.jpg',
            price: 90,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 8,
            countInStock: 80,
            description: 'A popular shirt',
        },
        {
            name: 'Second Shirt',
            slug: 'second-shirt',
            category: 'Shirts',
            image: '/images/shirt2.jpg',
            price: 190,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 8,
            countInStock: 8,
            description: 'Expensive popular shirt',
        },
        {
            name: 'Third Shirt',
            slug: 'third-shirt',
            category: 'Shirts',
            image: '/images/shirt3.jpg',
            price: 290,
            brand: 'Burberry',
            rating: 14.5,
            numReviews: 5,
            countInStock: 2,
            description: 'Luxury popular shirt',
        },
        {
            name: 'Free Pants',
            slug: 'free-pants',
            category: 'Pants',
            image: '/images/pants1.jpg',
            price: 90,
            brand: 'Nike',
            rating: 3.5,
            numReviews: 7,
            countInStock: 40,
            description: 'A popular pant',
        },
        {
            name: 'Second Pant',
            slug: 'second-pant',
            category: 'Pants',
            image: '/images/pants2.jpg',
            price: 90,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Expensive popular pants',
        },
        {
            name: 'Third Pant',
            slug: 'third-pant',
            category: 'Pants',
            image: '/images/pants3.jpg',
            price: 590,
            brand: 'Mayank',
            rating: 4.5,
            numReviews: 8,
            countInStock: 20,
            description: 'Luxury popular shirt',
        },
    ],
};

export default data;